1:
  shelf:
    top_left:
      x: 739
      y: 762
      z: 1507
    top_right:
      x: 1483
      y: 763
      z: 1489
    bottom_right:
      x: 1533
      y: 973
      z: 1376
    bottom_left:
      x: 720
      y: 970
      z: 1392

  moving_table:
    top_left:
      x: 598
      y: 356
      z: 2203
    top_right:
      x: 771
      y: 351
      z: 2203
    bottom_right:
      x: 758
      y: 570
      z: 2203
    bottom_left:
      x: 568
      y: 574
      z: 2203

2:
  cell_1:
    top_left:
      x: 739
      y: 762
      z: 1507
    top_right:
      x: 1483
      y: 763
      z: 1489
    bottom_right:
      x: 1533
      y: 973
      z: 1376
    bottom_left:
      x: 720
      y: 970
      z: 1392

  cell2:
    top_left:
      x: 598
      y: 356
      z: 2203
    top_right:
      x: 771
      y: 351
      z: 2203
    bottom_right:
      x: 758
      y: 570
      z: 2203
    bottom_left:
      x: 568
      y: 574
      z: 2203