1:
  shelf:
    top_left:
      x: 680
      y: 840
      z: 1507
    top_right:
      x: 1380
      y: 840
      z: 1489
    bottom_right:
      x: 1340
      y: 1030
      z: 1376
    bottom_left:
      x: 680
      y: 1030
      z: 1392

  moving_table:
    top_left:
      x: 0
      y: 0
      z: 0
    top_right:
      x: 0
      y: 0
      z: 0
    bottom_right:
      x: 0
      y: 0
      z: 0
    bottom_left:
      x: 0
      y: 0
      z: 0

2:
  cell_left:
    top_left:
      x: 35
      y: 491
      z: 3000
    top_right:
      x: 771
      y: 465
      z: 3000
    bottom_right:
      x: 771
      y: 126
      z: 3000
    bottom_left:
      x: 1
      y: 150
      z: 3000

  cell_right:
    top_left:
      x: 1250
      y: 490
      z: 3000
    top_right:
      x: 1879
      y: 461
      z: 3000
    bottom_right:
      x: 1920
      y: 115
      z: 3000
    bottom_left:
      x: 1270
      y: 125
      z: 3000