joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 250

egm_state_controller:
  type         : abb_egm_state_controller/EGMStateController
  publish_rate : 250

# These settings must match:
# - Joint names extracted from the ABB robot controller.
joint_group_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
