<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tuni_whitegoods_projection</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="jarvis-ur5@todo.todo">jarvis-ur5</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>opencv</depend>
  <depend>task_manager_msg</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
