##Description: Action that controls the human detection configuration

#goal definition
integration/HumanDetectionConfiguration new_configuration
integration/ActionRequest action_request
---
#result definition
integration/HumanDetectionConfiguration current_configuration
integration/ActionResult action_result
---
#feedback
integration/HumanDetectionConfiguration current_configuration
integration/ActionFeedback action_feedback
