##Description: Controls the execution of an already running schedule. Uses specific commands and provides feedback about the outcome of the command.

#goal definition
#this action cannot be cancelled
string schedule_id   #Required.If the schedule is is not currently managed, it is rejected.
string command #RESUME, STOP, PAUSE, CANCEL (Examples,tbd)
#If true the command will apply to the whole schedule
bool applies_to_all_schedule
#if appliesToAllSchedule==false then actions ids need to be specified. If no action ids are specified and appliesToAllSchedule==false, the command will be rejected.
string[] action_ids

##Command succeeds if schedule is running
string RESUME_SCHEDULE_EXECUTION=ResumeScheduleExecution
##Command succeeds if schedule is not running and not paused (Cannot be resumed)
##Stop will stop all actions ASAP
string STOP_SCHEDULE_EXECUTION=StopScheduleExecution
##Command succeeds if schedule is not running and paused
string PAUSE_SCHEDULE_EXECUTION=PauseScheduleExecution
##Command succeeds if schedule is not running and not paused (Cannot be resumed)
##Cancel will stop at the first possible/convenient occasion (in cancelable actions)
string CANCEL_SCHEDULE_EXECUTION=CancelScheduleExecution
##Note, for the moment cancel and stop will do the same.

integration/ActionRequest action_request
---
#result definition
integration/ActionResult action_result
---
#feedback
integration/ActionFeedback action_feedback


