##Description: Requests spawning some dynamic objects to a specific scene.

#The id of the related Scene
string scene_id

#The id of the applicable simulation instance
string simulation_id

#Requests to the assembly steps of specific instances.
integration/DynamicObjectAssembly[] hierarchy_requests

---
#result definition

#The id of the related Scene
string scene_id

#The id of the applicable simulation instance
string simulation_id

##Cumulative steps set, the list contains the instance_id. 
string[] successes
##Cumulative assembly step requests that could not be set OK, the list contains the instance_id. 
string[] errors
---
#feedback
##Feedback provision is optional.
#The id of the related Scene
string scene_id
#The id of the applicable simulation instance
string simulation_id

##Cumulative steps set, the list contains the instance_id. 
string[] successes
##Cumulative assembly step requests that could not be set OK, the list contains the instance_id. 
string[] errors