#Used to get a detection result as an action

##Define the available matching methods
string CAD_MATCH_DETECTION_METHOD= cad_matching
string SILHOUETTE_MATCH_DETECTION_METHOD= silhouette_matching
string detection_method #should use on of the matching methods defined in the constants above.

string detected_part_id #the id of the part to identify.
string region_of_interest_id #the id of the region of interest.
float64 offset_meters #distance in meters by which the estimated plane is shifted towards the camera
string parent_camera_frame_id #the camera frame used for the detection. Should be in TF
string result_frame_id #the frame_id that should be used for the detection result in TF.
uint32 refinement_level #-1 means automatic, The maximum level should be defined by the module. The more the better. In case refinement_level>max then the max should be used.

integration/ActionRequest action_request
---
#result definition
integration/ActionResult action_result
geometry_msgs/PoseStamped detection_result #The detection result, if the detection was successful.
uint32 refinement_level #The final refinement_level, used. 
---
#feedback
integration/ActionFeedback action_feedback
uint32 refinement_level #The current refinement_level