##Basic skill Action provided by the Easy Programming Tool


#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id

## The id of the marker/QR/April Tag to detect.
string docking_id
geometry_msgs/Transform relative_distance
---
#result definition
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id

---
#feedback
#Frequency of about 1 Hz should be OK
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id