##Description: Action that requests the execution of a task from a human operator.
##This is a syncronous request, the operator support module should ask the operator to complete the task when this action is triggered or reject the action if it is not possible to ask the operator to perform it.
##The details about the task should be acquired indirectly.

#goal definition
string ar_human_task_id
integration/ActionRequest action_request
---
#result definition
string ar_human_task_id
integration/ActionResult action_result
---
#feedback
string ar_human_task_id
integration/ActionFeedback action_feedback
