##Description: Action that requests the execution of a skill from a skill engine
##The details about the skill should be acquired indirectly.

#goal definition
string skill_id
integration/ActionRequest action_request
---
#result definition
string skill_id
integration/ActionResult action_result
---
#feedback
string skill_id
integration/ActionFeedback action_feedback
