##Description: Action that requests the projection of instructions
##The action is completed when the instructions have been shown. 
##The instructions remain projected until cancelled

#goal definition
Header header                        # header for frame information

string request_id
string projection_id #id of projection area where element should be displayed
string html #path to html or a string containg html content
float32 scale #scaling the content relative the the projection area
int32[2] shift #shifting content relative to the ipper-left corner of projection area

duration lifetime                    # How long the object should last before being automatically deleted.  0 means forever
bool frame_locked                    # If this marker should be frame-locked, i.e. retransformed into its frame every timestep
---
#result definition
string[] displayed_request_ids
---
#feedback
string[] displayed_request_ids
