##Description: Action that requests to switch the projection of an interface
#goal definition
Header header                        # header for frame information

string request_id
string resource_id                   #id of the interface to show
string zone                          #where to display text
---
#result definition
string[] displayed_request_ids
---
#feedback
string[] displayed_request_ids
