##Description: Project a safety border. Topic name and initial border are given as argument
##The action is completed when the projector start projecting the border. 

#goal definition
string request_id   #uniquely identifies this request.Subsequent requests overide previous request.
string zone
int32 position_row   #can be any value in case of dynamic border
int32 position_col   #can also be any value
geometry_msgs/PolygonStamped border  # the initial border to display, can be empty/null. In which case it should be ignored.
string border_topic                  # The safety border to follow is published in this topic. Its type is geometry_msgs/PolygonStamped
std_msgs/ColorRGBA border_color      # Color [0.0-1.0]
bool is_filled                       # if the inside border is filled
int32 thickness                      # thickness of border line 
duration lifetime                    # How long each safety border frame last  before being automatically deleted.  0 means forever
bool track_violations    #if true the projector interface publishes events on violation detection
---
#result definition
string[] displayed_request_ids
---
#feedback
string[] displayed_request_ids

