CONFIRM:
  img_path: CONFIRM.png
  loc:
  - 887
  - 1106
  size:
  - 163
  - 135
DEAD_MAN:
  img_path: DEAD_MAN.png
  loc:
  - 859
  - 1574
  size:
  - 168
  - 160
DM_NOT_PRESSED:
  img_path: DM_NOT_PRESSED.png
  loc:
  - 884
  - 662
  size:
  - 168
  - 160
GO:
  img_path: GO.png
  loc:
  - 881
  - 555
  size:
  - 146
  - 138
GRASP_ARM:
  img_path: GRASP_ARM.png
  loc:
  - 520
  - 195
  size:
  - 168
  - 160
MOTOR_FRAME:
  img_path: MOTOR_FRAME.png
  loc:
  - 540
  - 195
  size:
  - 168
  - 160
ROBOT_ACTIVE:
  img_path: ROBOT_ACTIVE.png
  loc:
  - 0
  - 667
  size:
  - 168
  - 160
ROCKER_SHAFT:
  img_path: ROCKER_SHAFT.png
  loc:
  - 540
  - 195
  size:
  - 168
  - 160
START_ROBOT:
  img_path: START_ROBOT.png
  loc:
  - 0
  - 662
  size:
  - 168
  - 160
STOP:
  img_path: STOP.png
  loc:
  - 878
  - 145
  size:
  - 149
  - 142
