// Generated by gencpp from file tuni_whitegoods_msgs/PointsDepthMap.msg
// DO NOT EDIT!


#ifndef TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAP_H
#define TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAP_H

#include <ros/service_traits.h>


#include <tuni_whitegoods_msgs/PointsDepthMapRequest.h>
#include <tuni_whitegoods_msgs/PointsDepthMapResponse.h>


namespace tuni_whitegoods_msgs
{

struct PointsDepthMap
{

typedef PointsDepthMapRequest Request;
typedef PointsDepthMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PointsDepthMap
} // namespace tuni_whitegoods_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMap > {
  static const char* value()
  {
    return "053187b90257a916cb98c3355d430439";
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMap&) { return value(); }
};

template<>
struct DataType< ::tuni_whitegoods_msgs::PointsDepthMap > {
  static const char* value()
  {
    return "tuni_whitegoods_msgs/PointsDepthMap";
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMap&) { return value(); }
};


// service_traits::MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMapRequest> should match
// service_traits::MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMap >
template<>
struct MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMap >::value();
  }
  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tuni_whitegoods_msgs::PointsDepthMapRequest> should match
// service_traits::DataType< ::tuni_whitegoods_msgs::PointsDepthMap >
template<>
struct DataType< ::tuni_whitegoods_msgs::PointsDepthMapRequest>
{
  static const char* value()
  {
    return DataType< ::tuni_whitegoods_msgs::PointsDepthMap >::value();
  }
  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMapResponse> should match
// service_traits::MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMap >
template<>
struct MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMap >::value();
  }
  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tuni_whitegoods_msgs::PointsDepthMapResponse> should match
// service_traits::DataType< ::tuni_whitegoods_msgs::PointsDepthMap >
template<>
struct DataType< ::tuni_whitegoods_msgs::PointsDepthMapResponse>
{
  static const char* value()
  {
    return DataType< ::tuni_whitegoods_msgs::PointsDepthMap >::value();
  }
  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAP_H
