// Generated by gencpp from file tuni_whitegoods_msgs/PointsDepthMapResponse.msg
// DO NOT EDIT!


#ifndef TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAPRESPONSE_H
#define TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace tuni_whitegoods_msgs
{
template <class ContainerAllocator>
struct PointsDepthMapResponse_
{
  typedef PointsDepthMapResponse_<ContainerAllocator> Type;

  PointsDepthMapResponse_()
    : poi_depth_map()  {
    }
  PointsDepthMapResponse_(const ContainerAllocator& _alloc)
    : poi_depth_map(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _poi_depth_map_type;
  _poi_depth_map_type poi_depth_map;





  typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PointsDepthMapResponse_

typedef ::tuni_whitegoods_msgs::PointsDepthMapResponse_<std::allocator<void> > PointsDepthMapResponse;

typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapResponse > PointsDepthMapResponsePtr;
typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapResponse const> PointsDepthMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator1> & lhs, const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator2> & rhs)
{
  return lhs.poi_depth_map == rhs.poi_depth_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator1> & lhs, const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuni_whitegoods_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a14e9f9688e30d57ed425a9c43605081";
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa14e9f9688e30d57ULL;
  static const uint64_t static_value2 = 0xed425a9c43605081ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuni_whitegoods_msgs/PointsDepthMapResponse";
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] poi_depth_map\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poi_depth_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointsDepthMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuni_whitegoods_msgs::PointsDepthMapResponse_<ContainerAllocator>& v)
  {
    s << indent << "poi_depth_map[]" << std::endl;
    for (size_t i = 0; i < v.poi_depth_map.size(); ++i)
    {
      s << indent << "  poi_depth_map[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.poi_depth_map[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAPRESPONSE_H
