// Generated by gencpp from file tuni_whitegoods_msgs/PointsDepthMapRequest.msg
// DO NOT EDIT!


#ifndef TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAPREQUEST_H
#define TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace tuni_whitegoods_msgs
{
template <class ContainerAllocator>
struct PointsDepthMapRequest_
{
  typedef PointsDepthMapRequest_<ContainerAllocator> Type;

  PointsDepthMapRequest_()
    : poi_rgb()  {
    }
  PointsDepthMapRequest_(const ContainerAllocator& _alloc)
    : poi_rgb(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _poi_rgb_type;
  _poi_rgb_type poi_rgb;





  typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PointsDepthMapRequest_

typedef ::tuni_whitegoods_msgs::PointsDepthMapRequest_<std::allocator<void> > PointsDepthMapRequest;

typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapRequest > PointsDepthMapRequestPtr;
typedef boost::shared_ptr< ::tuni_whitegoods_msgs::PointsDepthMapRequest const> PointsDepthMapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator1> & lhs, const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator2> & rhs)
{
  return lhs.poi_rgb == rhs.poi_rgb;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator1> & lhs, const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tuni_whitegoods_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ecbdb8dda7de62ad2fecb489d597c09";
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ecbdb8dda7de62aULL;
  static const uint64_t static_value2 = 0xd2fecb489d597c09ULL;
};

template<class ContainerAllocator>
struct DataType< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tuni_whitegoods_msgs/PointsDepthMapRequest";
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] poi_rgb\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poi_rgb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointsDepthMapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tuni_whitegoods_msgs::PointsDepthMapRequest_<ContainerAllocator>& v)
  {
    s << indent << "poi_rgb[]" << std::endl;
    for (size_t i = 0; i < v.poi_rgb.size(); ++i)
    {
      s << indent << "  poi_rgb[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.poi_rgb[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUNI_WHITEGOODS_MSGS_MESSAGE_POINTSDEPTHMAPREQUEST_H
