book_robot_static_border_server: execution/projector_interface/integration/actions/book_robot_static_border
release_robot_static_border_server: execution/projector_interface/integration/actions/release_robot_static_border
book_operator_static_border_server: execution/projector_interface/integration/actions/book_operator_static_border
release_operator_static_border_server: execution/projector_interface/integration/actions/release_operator_static_border
safety_border_server: execution/projector_interface/integration/actions/set_safety_border_projection

button_projection_server_name: execution/projector_interface/integration/actions/set_virtual_buttons_projection
button_color_server_name: execution/projector_interface/integration/actions/set_virtual_button_change_color
user_interface_server_name: execution/projector_interface/integration/actions/set_preset_ui_projection
unset_projection_server_name: execution/projector_interface/integration/actions/unset_projection
instruction_projection_server_name: execution/projector_interface/integration/actions/set_instructions_projection