<?xml version="1.0"?>
<package format="2">
  <name>tuni_whitegoods_view</name>
  <version>0.0.1</version>
  <description>
    ROS package for displaying and managing whitegoods views with OpenGL, OpenCV, ImGui, and integration with other ROS components.
  </description>

  <maintainer email="your_email@domain.com">Your Name</maintainer>
  <license>TBD</license>

  <buildtool_depend>catkin</buildtool_depend>
  
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>cv_bridge</build_depend>
  <build_depend>image_transport</build_depend>
  <build_depend>integration</build_depend>
  <build_depend>tf2</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>tf2_geometry_msgs</build_depend>
  <build_depend>tuni_whitegoods_msgs</build_depend>
  <build_depend>tuni_whitegoods_projector_interface</build_depend>
  <build_depend>eigen3</build_depend>

  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>integration</exec_depend>
  <exec_depend>tf2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>tuni_whitegoods_msgs</exec_depend>
  <exec_depend>tuni_whitegoods_projector_interface</exec_depend>
  <exec_depend>eigen3</exec_depend>

  <build_depend>opencv4</build_depend>
  <build_depend>libgl1-mesa-dev</build_depend>
  <build_depend>libglfw3-dev</build_depend>
  <build_depend>libglew-dev</build_depend>

  <exec_depend>message_runtime</exec_depend>



</package>