##Description: Action that controls the tools configuration

#goal definition
integration/ToolsConfiguration new_configuration
integration/ActionRequest action_request
---
#result definition
integration/ToolsConfiguration current_configuration
integration/ActionResult action_result
---
#feedback
integration/ToolsConfiguration current_configuration
integration/ActionFeedback action_feedback
