##Description: Action that requests a tool to open/close.

#goal definition
##If true, the tool is closed
string tool_action
string ENABLE=ENABLE
string DISABLE=DISABLE
string PRE_ENABLE=PRE_ENABLE
integration/ActionRequest action_request
---
#result definition
string tool_action
string ENABLE=ENABLE
string DISABLE=DISABLE
string PRE_ENABLE=PRE_ENABLE
integration/ActionResult action_result
---
#feedback
string tool_action
string ENABLE=ENABLE
string DISABLE=DISABLE
string PRE_ENABLE=PRE_ENABLE
integration/ActionFeedback action_feedback
