##High level skill Action provided by the Easy Programming Tool

##goal definition includes : Id of fan cowl, id of template (there are 3 templates per fan cowl), numbers of drills, id of drilling machine (perhaps some parameters are inferred)
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
#The id of the fan cowl to drill
string fan_cowl_id
#The id of the fan cowl template to use
string fan_cowl_template_id
#The id of the drilling machine
string drilling_machine_id
#Requested set of drills
string[] drills_needed

---
#result definition
#The current location
geometry_msgs/PoseStamped current_location
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
##Id of drilling hole
string[] drill_id
##Current drilling hole status (Pending, InProgress, OK, Failure)
string[] drill_status
##Drill attempts per hole
int32[] drill_attempts
---
#feedback
#Frequency of about 1 Hz should be OK
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
##High level action description: heading_to_origin, picking, transporting, placing, done
string action_description
##Modelling of status per drill
##Id of drilling hole
string[] drill_id
##Current drilling hole status (Pending, InProgress, OK, Failure)
string[] drill_status
##Drill attempts per hole
int32[] drill_attempts

string PENDING_DRILLING_STATUS=Pending
string IN_PROGRESS_DRILLING_STATUS=InProgress
string OK_DRILLING_STATUS=OK
string FAILURE_DRILLING_STATUS=Failure