##Description: Action that requests the execution of a task from a human operator.
##This is a syncronous request, the OSM Should ask the operator to complete the task when this action is triggered or reject the action if this is not possible.

#goal definition
integration/HumanTask human_task

#See HumanActionPurposes.msg purposes
string purpose
integration/ActionRequest action_request
---
#result definition
string task_id
integration/ActionResult action_result
---
#feedback
string task_id
integration/ActionFeedback action_feedback
