##High level skill Action provided by the Easy Programming Tool

##goal definition includes : Id of fan cowl, id of template (there are 3 templates per fan cowl), numbers of drills, id of drilling machine (perhaps some parameters are inferred)
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
#The id of the part to inspect
string part_id
#The id of zone of the part to inspect
string part_zone_id
#The operation mode to use, teaching mode or inspection mode
string operation_mode
string TEACHING_OPERATION_MODE=Teaching
string INSPETION_OPERATION_MODE=Inspection

---
#result definition
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
#Inspection result is either OK, (true) or Faulty (false). False indicates a successful inspection that shows a faulty part.
bool inspection_result_ok
---
#feedback
#Frequency of about 1 Hz should be OK
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id