#This action commands a mobile resource to move to specific waypoints.

#goal definition
geometry_msgs/PoseStamped[] waypoints
float32 timeout
integration/ActionRequest action_request
---
#result definition

integration/ActionResult action_result
---
#feedback
uint32 goal_index # current index of PoseStamped[] waypoints tracked
integration/ActionFeedback action_feedback

