##Description: Trigger Quality Inspection for a particular product

#goal definition
integration/QualityInspectionRequest[] quality_inspection_targets
---
#result definition
## A related image for reference
sensor_msgs/CompressedImage resource_image
integration/QualityInspectionResult[] quality_inspection_results
---
#feedback
integration/QualityInspectionResult[] quality_inspection_feedback