#This action signals the execution of an action that is referenced by an external id.

#goal definition
string reference_id ##reference to action details
integration/ActionRequest action_request
---
#result definition
integration/ActionResult action_result
---
#feedback
integration/ActionFeedback action_feedback
