##Description: release a location where the robot will be placing objects
##The action is completed when the projector start projecting the border. 

#goal definition
string request_id   #uniquely identifies this request.Subsequent requests overide previous request.
string id           #id of the border booked
int32 status        #status of the border 0 to release only this border and -1 to release all borders (including adjacent ones)
---
#result definition
string[] displayed_request_ids
---
#feedback
string[] displayed_request_ids