##High level skill Action provided by the Easy Programming Tool

#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
#The id of the product to screw
string product_id
#The id of the screws to screw during the execution of this skill
string[] screw_ids
#The id of the screwdriver
string screwdriver_id
---
#result definition
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
##Id of screw
string[] screw_ids
##Current screw id status (Pending, InProgress, OK, Failure)
string[] screw_status
---
#feedback
#Frequency of about 1 Hz should be OK
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
##Id of screw
string[] screw_ids
##Current screw id status (Pending, InProgress, OK, Failure)
string[] screw_status

string PENDING_STATUS=Pending
string IN_PROGRESS_STATUS=InProgress
string OK_STATUS=OK
string FAILURE_STATUS=Failure