##Description: Action that requests the projection of instructions
##The action is completed when the instructions have been shown. 
##The instructions remain projected until cancelled

#goal definition
Header header                        # header for frame information

string request_id
string zone                           #where to display text
geometry_msgs/Pose target_location
string title
std_msgs/ColorRGBA title_color           # Color [0.0-1.0]

string description
std_msgs/ColorRGBA description_color     # Color [0.0-1.0]

duration lifetime                    # How long the object should last before being automatically deleted.  0 means forever
---
#result definition
string[] displayed_request_ids
---
#feedback
string[] displayed_request_ids
