##Description: Action that requests the projection of instructions
##The action is completed when the instructions have been shown. 
##The instructions remain projected until cancelled

uint8 ARROW=0
uint8 RECTANGLE=1
uint8 CIRCLE=2
uint8 TRIANGLE=3

#goal definition
Header header                        # header for frame information
geometry_msgs/Vector3 scale             # Scale of the object 1,1,1 means default 1 meter square
string request_id
geometry_msgs/Pose target_location
int32 type                               #Determines the shape
std_msgs/ColorRGBA colour           # Color [0.0-1.0]

duration lifetime                    # How long the object should last before being automatically deleted.  0 means forever
bool frame_locked                    # If this marker should be frame-locked, i.e. retransformed into its frame every timestep
integration/ActionRequest action_request
---
#result definition
string[] displayed_request_ids
integration/ActionResult action_result
---
#feedback
string[] displayed_request_ids
integration/ActionFeedback action_feedback
