##Description: Action that requests the setup of a layout for static borders
##The action is completed when the instructions have been received and the border manager launched. 
##The instructions remain projected until cancelled

#goal definition
Header header                        # header for frame information

string request_id
int32 size_rows                           #number of rows
int32 size_cols
float32 safety_factor                     #scale the diagonal of a border by this factor for hand detection
bool book_adjacent                        #book adjacents borders, useful if robot cross several borders

std_msgs/ColorRGBA status_booked           # Color [0.0-1.0]
std_msgs/ColorRGBA status_free     # Color [0.0-1.0]
std_msgs/ColorRGBA status_operator     # Color [0.0-1.0]

---
#result definition
string[] displayed_request_ids
---
#feedback
string[] displayed_request_ids