##Description: Shows a message to Human Operator, a MODE can be specified for the message.
##The server should automatically make the message dissapear without requiring any operator action.

#goal definition
string title
string message
#See HumanActionPurposes.msg MODES
string mode
integration/ActionRequest action_request
---
#result definition
integration/ActionResult action_result
---
#feedback
integration/ActionFeedback action_feedback
