##Description: Initiates a schedule simulation and allows the caller to observe the results.
##The simulation finishes when the SimulateCompleted.srv is called for this simulation.

#goal definition
string simulationId #Provided by the caller for reference
string sceneId #References the simulation scene that should be used during the simulation. 
integration/SimulationResourceStatus[] simulationResourcesInitialStatus
bool requestActionSimulationResults #if true detailed, action level results will be provided
integration/ActionRequest action_request
---
#result definition
bool requestActionSimulationResults #if true detailed, action level results will be provided
#The simulation results
integration/SimulationResourceStatus[] simulationResourcesFinalStatus
integration/ScheduleSimulationResult scheduleSimulationResult 
integration/ActionResult action_result
---
#feedback
#Feedback here is only meant to show info about the simulation that is in progress.
bool requestActionSimulationResults #if true detailed, action level results will be provided
integration/SimulationResourceStatus[] simulationResourcesIntermediateStatus
integration/ScheduleSimulationResult scheduleSimulationResult 
integration/ActionFeedback action_feedback


