##High level skill Action provided by the Easy Programming Tool

##goal definition includes : Inputs: Origin, Destination, id of the fan cowl
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
#The id of a known location to place the fan cowl
string fan_cowl_origin_id
#The id of a known location to place the fan cowl
string fan_cowl_destination_id
#The id of the fan cowl to transfer
string fan_cowl_id
---
#result definition
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
---
#feedback
#Frequency of about 1 Hz should be OK
#A unique request id provided per request, provided in goal and repeated in feedback&result
string request_id
