##Description: Action that stops projection of all information types

#goal definition
string request_id
integration/ActionRequest action_request
---
#result definition
string[] displayed_request_ids
integration/ActionResult action_result
---
#feedback
string[] displayed_request_ids
integration/ActionFeedback action_feedback
