#This action waits for a predetermined amount of time.
#goal definition

integration/ActionRequest action_request
---
#result definition
integration/ActionResult action_result
---
#feedback
integration/ActionFeedback action_feedback
