robot_base: base
depth_camera: rgb_camera_link

sub_points: /voxel_grid_master/output
topic_pcl_master: /kinect_master/cloud_robot_frame
topic_pcl_sub: /kinect_sub/cloud_robot_frame 

topic_depth: /depth/image_raw
topic_depth_to_rgb: /depth_to_rgb/image_raw

number_cam: 1

hand_tracking_rgb_coordinates: /hand_tracking/rgb/coordinates
hand_tracking_dm_coordinates: /hand_tracking/dm/coordinates

master_to_base: [0.328566, 0.627672, 1.668979, 0.912662, -0.357711, 0.075467, -0.182745]
